Models/Device.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BeOn.Models
{
    [Table("device")]
    public  class Device
    {
        [Column("id_device")]
        [Key]
        public virtual String DeviceId { get; set; }

        [Column("name")]
        public virtual string Name { get; set; }

        [Column("pac")]
        public virtual string Pac { get; set; }

        [Column("endproductcertificate")]
        public virtual string EndProductCertificate { get; set; }
        public virtual ICollection<EnvironmentPayload> EnvironmentPayloads { get; set; }
        public virtual ICollection<PositionningPayload> PositionningPayloads { get; set; }
       
    }
}

Models/EnvironmentPayload.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace BeOn.Models
{
    [Table("environment_payload")]
    public class EnvironmentPayload
    {
        [Column("id_device")]
        public String DeviceId { get; set; }
        public virtual Device Device { get; set; }

        [Column("timestampevent")]
        public DateTime TimestampEvent { get; set; }
        public virtual String TimestampEventToString { get { return $"{TimestampEvent.Day}/{TimestampEvent.Month}/{TimestampEvent.Year}  {TimestampEvent.Hour}:{TimestampEvent.Minute}" ; }  }

        [Column("seq_number")]
        public int SeqNumber { get; set; }

        [Column("computed_latitude")]
        public double ComputedLatitude { get; set; }
        public string ComputedLatitudeFormatted { get { return Convert.ToString(Math.Round(ComputedLatitude, 6)).Replace(",","."); } }

        [Column("computed_longitude")]
        public double ComputedLongitude { get; set; }
        public string ComputedLongitudeFormatted { get { return Convert.ToString(Math.Round(ComputedLongitude, 6)).Replace(",", "."); } } 

        [Column("radius")]
        public int Radius { get; set; }
       
        [Column("source")]
        public int Source { get; set; }
        
        [Column("status")]
        public int Status { get; set; }

        [Column("frametype")]
        public string Frametype { get; set; }

        [Column("batterylvl")]
        public double Batterylvl {get; set; }

        [Column("timestamppayload")]
        public DateTime DatePayload { get; set; }

        [Column("event_type")]
        public string EventType{ get; set; }

        [Column("tmax")]
        public int Tmax { get; set; }

        [Column("tmin")]
        public int Tmin { get; set; }

        [Column("tmean")]
        public int Tmean { get; set; }

        [Column("total_alert_duration")]
        public int TotalAlertDuration { get; set; }
      
        [Column("smax")]
        public double Smax { get; set; }

        [Column("total_shock")]
        public double TotalShock { get; set; }

        [Column("cptshockovlastperiod")]
        public int Cptshockovlastperiod { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace BeOn.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PositionningPayload.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace BeOn.Models
{
    [Table("positionning_payload")]
    public class PositionningPayload
    {
        [Column("id_device")]
        public String DeviceId { get; set; }
        public virtual Device Device { get; set; }

        [Column("timestampevent")]
        public DateTime TimestampEvent { get; set; }

        [Column("seq_number")]
        public int SeqNumber { get; set; }

        [Column("computed_latitude")]
        public double ComputedLatitude { get; set; }
        public string ComputedLatitudeFormatted { get { return Convert.ToString(Math.Round(ComputedLatitude, 6)).Replace(",", "."); } }

        [Column("computed_longitude")]
        public double ComputedLongitude { get; set; }
        public string ComputedLongitudeFormatted { get { return Convert.ToString(Math.Round(ComputedLongitude, 6)).Replace(",", "."); } }

        [Column("radius")]
        public int Radius { get; set; }

        [Column("source")]
        public int Source { get; set; }

        [Column("status")]
        public int Status { get; set; }

        [Column("frametype")]
        public string Frametype { get; set; }

        [Column("batterylvl")]
        public double Batterylvl { get; set; }

        [Column("timestamppayload")]
        public DateTime TimestampPayload { get; set; }
        [Column("event_type")]
        public string EventType { get; set; }
        [Column("long")]
        public double Long { get; set; }

        [Column("lat")]
        public double Lat { get; set; }

        [Column("alt")]
        public int Alt { get; set; }

        [Column("hdop")]
        public int Hdop { get; set; }

        [Column("nb_satellites")]
        public int NbSatellites { get; set; }
    }
}

Controllers/BeOnController.cs
using BeOn.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace BeOn.Controllers
{
	public class BeOnController : Controller
	{
		private readonly BeOnContext _context;
		public BeOnController(BeOnContext injectedBeonContext)
        {
			_context = injectedBeonContext;
        }
		public IActionResult Index()
		{
			return View();
		}
		public IActionResult Overview()
		{
			IEnumerable<Device> devices =  (from a in _context.Devices select a ).ToList(); //need add toList() -> conflict with List Devices --->NpgsqlOperationInProgressException: A command is already in progress
			return View(devices);
		}
		public IActionResult ListDevices()
		{
			IEnumerable<Device> devices = (from a in _context.Devices select a).ToList(); //need add toList() -> conflict with overview --->  NpgsqlOperationInProgressException: A command is already in progress

			return View(devices);
		}
		public IActionResult Dashboard(string IdDevice)
		{
			
			IQueryable<Device> devices = from a in _context.Devices where(a.DeviceId == IdDevice) select a;
			Device device = devices.First();
			if(device.EnvironmentPayloads.Count == 0)
            {
				return View("Default");
            }
			return View(device);
		}
		public IActionResult Location1Device(string IdDevice)
		{
			IQueryable<Device> devices = from a in _context.Devices where (a.DeviceId == IdDevice) select a;
			Device device = devices.First();
			return View(device);
		}	
		
		public IActionResult Temp(string IdDevice)
		{
			IQueryable<Device> devices = from a in _context.Devices where (a.DeviceId == IdDevice) select a;
			Device device = devices.First();
			return View(device);
		}

	}
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BeOn.Models;

namespace BeOn.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/BeOn/Default.cshtml
@{
    ViewData["Title"] = "Test Dashboard";
    Layout = "~/Views/Shared/_LayoutBeonDashboard.cshtml";
}

Views/BeOn/Index.cshtml
@{
    ViewData["Title"] = "View";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeOn</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/beon.css" />

</head>
<body>

    <div class="text-center">
        <h1 class="display-4"><img src="~/logoBeOn.png" alt="logo beon" class="" style="width:50vh" /></h1>
        <button type="button" class="btn btn-info btn-lg "> <a asp-controller="Beon" asp-action="Overview" style="color:#FFFF"> Enter</a> </button>
    </div>

</body>
</html>

Views/BeOn/ListDevices.cshtml
@model IEnumerable<Device>

@{
    ViewData["Title"] = "listDevices";
    Layout = "~/Views/Shared/_LayoutBeonPrincipal.cshtml";
    IEnumerable<Device> devices = Model;
}
@{
    bool alert = false;
    <script>
        let alertExist = false;
    </script>

    foreach (var device in devices)
    {
        if (device.EnvironmentPayloads.Count != 0)
        {
            IEnumerable<EnvironmentPayload> environmentPayloadsOrderByAsc1 = device.EnvironmentPayloads.OrderBy(a => a.TimestampEvent);
            EnvironmentPayload environmentLast1 = environmentPayloadsOrderByAsc1.Last();
            IEnumerable<EnvironmentPayload> env72alert1 = environmentPayloadsOrderByAsc1.Where(e => e.TimestampEvent > environmentLast1.TimestampEvent.AddHours(-72));

            foreach (var env in env72alert1)
            {
                if (env.EventType == "1" || env.EventType == "3")
                {
                    alert = true;
                    <script>
                        alertExist = true;
                    </script>
                    break;
                }
            }
        }
    }
}
<section class="d-flex flex-column-reverse flex-lg-row">
    <article class="container-fluid p-0">
        <div class="border m-3 m-lg-0">

            <div class="border p-3">
                <h3 class="text-left  ">Tracker List</h3>
            </div>
            <table class="table ">
                <caption class="d-none"> Tracker list </caption>
                <thead>
                    <tr>
                        <th scope="col">Device Id</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Device dev in Model)
                    {
                        <tr>
                            @if (dev.EnvironmentPayloads.Count != 0)
                            {
                                <th scope="row"> <a asp-controller="Beon" asp-action="Dashboard" asp-route-IdDevice="@dev.DeviceId"> @dev.DeviceId</a></th>
                            }
                            else
                            {
                                <th scope="row">  @dev.DeviceId <i class="text-muted">No data available</i></th>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </article>
    <aside class="d-flex flex-column flex-lg-row-reverse m-3 mr-lg-0  p-0  ">
        <div class="h-100 p-0 mr-2 text-center">
            <a class="btn btn-light border h-100  " data-bs-toggle="collapse" href="#alertCollapse" role="button" aria-expanded="false" aria-controls="alertCollapse" onclick="ChangeArrow(alertExist)">
                <span class="position-relative d-none d-lg-flex" style="top:50%;">
                    <img src="~/Icons/left-arrow.svg" alt="" id="arrowLeft" /><img src="~/Icons/right-arrow.svg" alt="" class="d-none" id="arrowRight" />&nbsp
                    @{ if (alert)
                        { <img src="~/Icons/notificationBell.svg" alt="" />}
                        else
                        {<img src="~/Icons/notification.svg" alt="" />} }
                </span>
                <span class="position-relative d-flex flex-column-reverse d-lg-none " style="top:50%;">
                    <img src="~/Icons/down-arrow.svg" alt="" id="arrowDown" /><img src="~/Icons/up-arrow.svg" alt="" class="d-none" id="arrowUp" />&nbsp
                    @{ if (alert)
                        { <img src="~/Icons/notificationBell.svg" alt="" />}
                        else
                        {<img src="~/Icons/notification.svg" alt="" />} }
                </span>
            </a>
        </div>
        @{ if (alert)
            {
        <div class="row" >
            <div class="col text-center" style="width:max-content;">
                <div class="collapse" id="alertCollapse">
                    <div class="card card-body" style="height: 80vh;  overflow-y: scroll;">
                        @{
                            string flag = "";
                            foreach (var device in devices)
                            {
                                if (device.EnvironmentPayloads.Count != 0)
                                {

                                    IEnumerable<EnvironmentPayload> environmentPayloadsOrderByAsc = device.EnvironmentPayloads.OrderBy(a => a.TimestampEvent);
                                    EnvironmentPayload environmentLast = environmentPayloadsOrderByAsc.Last();
                                    IEnumerable<EnvironmentPayload> env72alert = environmentPayloadsOrderByAsc.Where(e => e.TimestampEvent > environmentLast.TimestampEvent.AddHours(-72));


                                    foreach (var env in env72alert)
                                    {

                                        if ((env.EventType == "1" || env.EventType == "3") && flag != device.DeviceId)
                                        {
                                            <div class="dropdown-divider"></div>
                                            <div>
                                                <p>
                                                    Device:  @device.DeviceId
                                                </p>
                                                <p>
                                                    Last contact: <br /> @environmentLast.TimestampEvent
                                                </p>
                                                <p>
                                                    <a asp-controller="Beon" asp-action="Dashboard" asp-route-IdDevice="@device.DeviceId">Link to dashboard</a>
                                                </p>
                                            </div>
                                            <div class="dropdown-divider"></div>
                                            flag = device.DeviceId;
                                        }
                                        if (env.EventType == "1")
                                        {
                                            <div class="alertedcolorred">
                                                <p> <img src="~/Icons/heat.svg" alt="" />  Temperature Alert    -   @env.TimestampEvent.ToString("dd/MM/yy H:mm")</p>
                                            </div> 
                                        }                                        
                                        else if (env.EventType == "3")
                                        {
                                            <div class="alertcolorblue ">
                                                <p><img src="~/Icons/warningBlueBeon.svg" alt="">  Shock Alert    -   @env.TimestampEvent.ToString("dd/MM/yy H:mm")</p>
                                            </div> }
                                        else
                                        {
                                            continue;
                                        }
                                    }
                                }
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
            }
        }
    </aside>
</section>

Views/BeOn/Overview.cshtml
@model IEnumerable<Device>
@{
    ViewData["Title"] = "Overview";
    Layout = "~/Views/Shared/_layoutBeonPrincipal.cshtml";
    IEnumerable<Device> devices = Model;
}
@{
    bool alert = false;
    <script>
        let alertExist = false;
    </script>
    foreach (var device in devices)
    {
        if (device.EnvironmentPayloads.Count != 0)
        {
            IEnumerable<EnvironmentPayload> environmentPayloadsOrderByAsc1 = device.EnvironmentPayloads.OrderBy(a => a.TimestampEvent);
            EnvironmentPayload environmentLast1 = environmentPayloadsOrderByAsc1.Last();
            IEnumerable<EnvironmentPayload> env72alert1 = environmentPayloadsOrderByAsc1.Where(e => e.TimestampEvent > environmentLast1.TimestampEvent.AddHours(-72));

            foreach (var env in env72alert1)
            {
                if (env.EventType == "1" || env.EventType == "3")
                {
                    alert = true;
                    <script>
                        alertExist = true;
                    </script>
                    break;
                }
            }
        }
    }
}
<section class="d-flex flex-column-reverse flex-lg-row">
    <article class="container-fluid p-0">

        <div class="card m-3 m-lg-3 ">
            <div class="card-header pb-0 " style=" color: #201063;">
                <h5 class="card-title " style="font-weight: bold;"><img src="~/Icons/mapBlueBeon.svg" alt="" /> Overview</h5>
            </div>
            <div class="card-body">
                <div id="overview"></div>
            </div>
        </div>
    </article>
    <aside class="d-flex flex-column flex-lg-row-reverse m-3 m-lg-0 mt-lg-3 mb-lg-3 p-0  ">
        <div class="h-100 p-0 mr-2 text-center">
            <a class="btn btn-light border h-100  " data-bs-toggle="collapse" href="#alertCollapse" role="button" aria-expanded="false" aria-controls="alertCollapse" onclick="ChangeArrow(alertExist)">
                <span class="position-relative d-none d-lg-flex" style="top:50%;">
                    <img src="~/Icons/left-arrow.svg" alt="" id="arrowLeft" /><img src="~/Icons/right-arrow.svg" alt="" class="d-none" id="arrowRight" />&nbsp
                    @{ if (alert)
                        { <img src="~/Icons/notificationBell.svg" alt="" />}
                        else
                        {<img src="~/Icons/notification.svg" alt="" />} }
                </span>
                <span class="position-relative d-flex flex-column-reverse d-lg-none " style="top:50%;">
                    <img src="~/Icons/down-arrow.svg" alt="" id="arrowDown" /><img src="~/Icons/up-arrow.svg" alt="" class="d-none" id="arrowUp" />&nbsp
                    @{ if (alert)
                        { <img src="~/Icons/notificationBell.svg" alt="" />}
                        else
                        {<img src="~/Icons/notification.svg" alt="" />} }
                </span>
            </a>
        </div>
        @{ if (alert)
            {
                <div class="row" >
                    <div class="col text-center" style="width:max-content;">
                        <div class="collapse" id="alertCollapse">
                            <div class="card card-body" style="height: 80vh;  overflow-y: scroll;">
                                @{
                                    string flag = "";
                                    foreach (var device in devices)
                                    {
                                        if (device.EnvironmentPayloads.Count != 0)
                                        {

                                            IEnumerable<EnvironmentPayload> environmentPayloadsOrderByAsc = device.EnvironmentPayloads.OrderBy(a => a.TimestampEvent);
                                            EnvironmentPayload environmentLast = environmentPayloadsOrderByAsc.Last();
                                            IEnumerable<EnvironmentPayload> env72alert = environmentPayloadsOrderByAsc.Where(e => e.TimestampEvent > environmentLast.TimestampEvent.AddHours(-72));


                                            foreach (var env in env72alert)
                                            {

                                                if ((env.EventType == "1" || env.EventType == "3") && flag != device.DeviceId)
                                                {
                                                    <div class="dropdown-divider"></div>
                                                    <div>
                                                        <p>
                                                            Device:  @device.DeviceId
                                                        </p>
                                                        <p>
                                                            Last contact: <br /> @environmentLast.TimestampEvent
                                                        </p>
                                                        <p>
                                                            <a asp-controller="Beon" asp-action="Dashboard" asp-route-IdDevice="@device.DeviceId">Link to dashboard</a>
                                                        </p>
                                                    </div>
                                                    <div class="dropdown-divider"></div>
                                                    flag = device.DeviceId;
                                                }
                                                if (env.EventType == "1")
                                                {
                                                    <div class="alertedcolorred">
                                                        <p><img src="~/Icons/heat.svg" alt="" />  Temperature Alert    -   @env.TimestampEvent.ToString("dd/MM/yy H:mm")</p>
                                                    </div> }
                                                else if (env.EventType == "3")
                                                {
                                                    <div class="alertcolorblue ">
                                                        <p> <img src="~/Icons/warningBlueBeon.svg" alt="">  Shock Alert    -   @env.TimestampEvent.ToString("dd/MM/yy H:mm")</p>
                                                    </div> }
                                                else
                                                {
                                                    continue;
                                                }
                                            }
                                        }
                                    }
                                }
                            </div>
                        </div>
                    </div>
                </div>
        }
    }
    </aside>
</section>
<script type="text/javascript">

let devicesEnvironmentInfos = new Array();
@{string latitude = "43.7384";
        string longitude = "7.4246";
        double sMax = 0;
        double totalShock = 0;
        String lastContact = "";
        Int32 tMean = 0;
        Int32 batteryLvl = 0;
}
@{ foreach (Device device in devices)
    {
        if (device.EnvironmentPayloads.Count != 0)
        {

            IEnumerable<EnvironmentPayload> environmentPayloads = device.EnvironmentPayloads.OrderByDescending(e => e.TimestampEvent);
            double latitudeDouble = Math.Round(environmentPayloads.First().ComputedLatitude, 6);
            double longitudeDouble = Math.Round(environmentPayloads.First().ComputedLongitude, 6);
            latitude = latitudeDouble.ToString().Replace(',', '.');
            longitude = longitudeDouble.ToString().Replace(',', '.');
            lastContact = environmentPayloads.First().TimestampEventToString;
            sMax = environmentPayloads.First().Smax;
            totalShock = environmentPayloads.First().TotalShock;
            tMean = environmentPayloads.First().Tmean;
            batteryLvl = Convert.ToInt32(environmentPayloads.First().Batterylvl);
        }
        else if (device.PositionningPayloads.Count != 0)
        {
            IEnumerable<PositionningPayload> positionningPayloads = device.PositionningPayloads.OrderByDescending(e => e.TimestampEvent);
            double latitudeDouble = Math.Round(positionningPayloads.First().ComputedLatitude, 6);
            double longitudeDouble = Math.Round(positionningPayloads.First().ComputedLongitude, 6);
            latitude = latitudeDouble.ToString().Replace(',', '.');
            longitude = longitudeDouble.ToString().Replace(',', '.');
            sMax = 0;
            totalShock = 0;
            lastContact = "no environment info";
            tMean = 0;
            batteryLvl = 0;
        }
        else
        {
            latitude = " 43.5333";
            longitude = " 1.35366";
            sMax = 0;
            totalShock = 0;
            lastContact = "no environment and positionning info";
            tMean = 0;
            batteryLvl = 0;
        }

        <Text>
            var deviceInfos = ('"@device.DeviceId": {"lat":' +  @latitude + ',"lon":' + @longitude + ',"batteryLvl":' + @batteryLvl +',"sMax":' + @sMax  + ',"totalShock":' + @totalShock  + ',"tMean":' + @tMean + ',"lastContact": "@lastContact"}');
            devicesEnvironmentInfos.push(deviceInfos);
        </Text>
    }
}
</script>
<script src="~/js/scriptOverview.js"></script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "View";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeOn</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/beon.css" />

</head>
<body class="d-flex" style="height:100vh;width:100vw">

<div class="text-center m-auto">
    <h1 class="display-4"><img src="~/logoBeOn.png" alt="logo beon" class="" style="width:50vh; max-width:100%;"/></h1>
    <button type="button" class="btn btn-info btn-lg mb-5 "> <a asp-controller="Beon" asp-action="Overview" style="color:#FFFF"> Enter</a> </button>
</div>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeOn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeOn</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BeOn" asp-action="Index">Beon</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BeOn - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>